### ISSUE TITLE
Splash Screen, tablet/mobile: remove wording

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/utahFossilGuide#1]
### Where is the text you are suggesting changes for?

Splash Screen on tablet and mobile only

### What do you propose the new text says?

Need to remove "from UGS' web application, Utah Rockhounder"

This change could potentially be made in the source code on the server.

**Comment by geowomansteph** [comment]
Ok....do I need to review something?

**Comment by Mackenzie-Cope** [comment]
nope, sorry! This was a quick fix that didn't make it to tablet and mobile is all. Didn't mean to assign you @geowomansteph!

This has already been fixed in the server files by Marshall.
